### ISSUE TITLE
License Discussion

### ISSUE THREAD

**Issue by hellosakshi** [UBC-MDS/easymlr#23]
Hey guys,

I am opening an issue to select License for our project. I suggest to visit [choosealicense.com](choosealicense.com). From there you can browse and come up with your personal preferences. From there we will have a discussion about the pros/cons of each of the license preferences.

Finally we will vote on a single license to proceed with. 

**Sakshi's preference:**

**1. MIT License:**
I selected this license because it is simple and covers the basic usage for our project. We're already using it.  I believe the MIT License is a good idea  and everyone is familiar with it. It helps our package viewers to understand the copyright rules of our project. Also, I think the conditions outlined in the MIT License serve the purpose of our project well. Namely, it let's others do what they want with our project while preserving the copyright.

**2. Boost Software License 1.0:** 
This one is also similar to the MIT license. The Boost License goes into a little more detail about what the users are permitted to do. However, I  never heard of this license before. Also, I believe this license might hinder others to use our package.

**Comment by yzr1996** [comment]
Here is the link of choose license: [choosealicense.com](https://choosealicense.com/)

Personally, I agree with Sakshi's opinion to keep using MIT License. I think our package welcomeeveryone to use, and contribute.

**Comment by larahabashy** [comment]
Since our package is meant for folks who aren't necessarily super comfortable using tools such as GitHub, I think for simplicity, and to encourage users to collaborate, we should carry on using the MIT license. Agreed with you Sakshi and Eric!

**Comment by IfyAnene7** [comment]
I also agree with Sakshi's recommendations. A licence that encourages distribution, modification, private use and can be used in commercial settings seems ideal.
